detector_node:
  ros__parameters:
    network:
      config: "$(find-pkg-share openrobotics_darknet_ros)/yolo-v7/yolov7.cfg"
      weights: "$(find-pkg-share openrobotics_darknet_ros)/yolo-v7/yolov7.weights"
      class_names: "$(find-pkg-share openrobotics_darknet_ros)/yolo-v7/coco.names"
    detection:
      threshold: 0.25
      nms_threshold: 0.45
